### PR TITLE
[oneMKL: BLAS] bug fix for ldc parameter

### PR DESCRIPTION
**Pull request by mmeterel**
This PR is fixing bugs for ldc parameter.

### CODE REVIEW

**Comment by mmeterel** [comment]
@andrewtbarker Could you please take a look at this?

**Review by andrewtbarker — APPROVED** [review]
Thanks for fixing this!

**Comment by mmeterel** [comment]
@rscohn2  Could you please merge this if you don't see any issues?

**Comment by mmeterel** [comment]
@rscohn2 Could you please merge this PR?

**Comment by rscohn2** [comment]
Should we add some more people from MKL with commit rights?

**Comment by mmeterel** [comment]
> Should we add some more people from MKL with commit rights?

That would be a good idea. The question would be, 1 person per domain (e.g. BLAS, DFT..) or 1-2 persons for entire oneMKL?
@spencerpatty Any idea?

**Comment by spencerpatty** [comment]
1 or 2 from oneMKL is sufficient.  This is a small change.  I can be one of them :)

**Review by spencerpatty — COMMENTED** [review]
looks good to me

**Comment by mmeterel** [comment]
> 1 or 2 from oneMKL is sufficient. This is a small change. I can be one of them :)

@spencerpatty 
The question here is this:
For PRs coming from oneMKL, we can assign a person from our domain for approval. But nobody from oneMKL (as far as I know) has merging rights to oneAPI spec. So, we have to ask to @rscohn2 each time. The question here is, how many people from oneMKL should have merge/write access to this repo? One from each oneMKL domain? or 1-2 people from entire oneMKL that will be responsible for all RPs coming from oneMKL?

**Comment by rscohn2** [comment]
@spencerpatty @mkrainiuk @ericlars already have write access. I can add more.

**Comment by mmeterel** [comment]
> @spencerpatty @mkrainiuk @ericlars already have write access. I can add more.

Oh, did not know. I can represent BLAS domain.

**Comment by rscohn2** [comment]
> Oh, did not know. I can represent BLAS domain.

You should get a notification by end of day.

**Pull request merged**
