### PR TITLE
[oneDPL] Added default value for the make_device_policy template parameter

### PR DESCRIPTION
**Pull request by capatober**

### CODE REVIEW

**Comment by capatober** [comment]
@akukanov, could you please check if it's an issue that should be fixed or implementation details?

**Comment by akukanov** [comment]
Yes it's an issue to be fixed, because as we saw the default template parameter is needed in order to use the function with no explicit arguments.

**Comment by rscohn2** [comment]
Making a release. Please merge or close.

**Comment by capatober** [comment]
@akukanov, can we merge it? I don't have enough rights for merging.

**Comment by rscohn2** [comment]
I can merge if you confirm it is ready.

**Comment by capatober** [comment]
I think it's ready. @akukanov, what is your opinion?

**Comment by rscohn2** [comment]
Closing because it is inactive. You can reopen if you are still working on it.

**Pull request closed without merging**
