### PR TITLE
Update oneVPL to 2.4.0

### PR DESCRIPTION
**Pull request by akwrobel**

### CODE REVIEW

**Comment by rscohn2** [comment]
My intention was to add release notes for the latest and leave older release notes. See here for an example
https://spec.oneapi.com/releases/index.html#id2

**Comment by akwrobel** [comment]
@rscohn2 This was one of my opens to @IgorBelyakovIntel with this update and the request was replacement.  I don't have any objections to this new formatting, and I'll push a change inline with this request shortly

**Comment by rscohn2** [comment]
If someone has a strong preference for replacement over cumulative, then let me know so we can discuss it.

**Comment by akwrobel** [comment]
@rscohn2 No strong opposition.  Igor indicated I should check with you if there were any questions.  
https://github.com/oneapi-src/oneAPI-spec/pull/331

**Pull request merged**
