### PR TITLE
Work around spacing problems in C++ function signatures

### PR DESCRIPTION
**Pull request by rsdubtso**
https://github.com/readthedocs/sphinx_rtd_theme/issues/647

This probably requires an ack from owners of other parts of the spec.

### CODE REVIEW

**Comment by rscohn2** [comment]
[HTML version](http://staging.spec.oneapi.com.s3-website-us-west-2.amazonaws.com/exclude/ci/branches/refs/heads/onednn/css_fix/versions/latest/index.html)

**Comment by rsdubtso** [comment]
> [HTML version](http://staging.spec.oneapi.com.s3-website-us-west-2.amazonaws.com/exclude/ci/branches/refs/heads/onednn/css_fix/versions/latest/index.html)

Hi @rscohn2 , this link does not work for me. I can add a rendered version in my repo if you want to have that.

**Comment by rscohn2** [comment]
@mkrainiuk, @andreynv, @IgorBelyakovIntel: This change fixes the problem where there isn't any space between type type and the parameter name in a sphinx function directive. It only happens when the type is cross-referenced.  I spot-checked DAL & MKL and don't see any negative impact.

Here is an example of a [problem](http://staging.spec.oneapi.com.s3-website-us-west-2.amazonaws.com/exclude/ci/branches/refs/heads/onednn/css_fix/versions/latest/index.html) and here is how it looks when it is [fixed](http://staging.spec.oneapi.com.s3-website-us-west-2.amazonaws.com/exclude/ci/branches/refs/heads/onednn/css_fix/versions/latest/index.html).

We can let Roma merge this change. If we later see a problem, it will be trivial to back out.

**Comment by rscohn2** [comment]
@rsdubtso It is curious that it doesn't work. Please add your link if you have something convenient.

**Comment by rsdubtso** [comment]
[Original](https://spec.oneapi.com/versions/latest/elements/oneDAL/source/algorithms/clustering/kmeans.html#_CPPv4N6onedal6kmeans5model9centroidsE)

[Fixed](https://rsdubtso.github.io/oneapi-spec/versions/latest/elements/oneDAL/source/algorithms/clustering/kmeans.html#_CPPv4N6onedal6kmeans5model9centroidsE)

**Comment by rsdubtso** [comment]
I'll let it sit here for one more day and then merge it. I think it makes sense to publish this and #158 before 0.9.

**Comment by rlnx** [comment]
@rsdubtso, @rscohn2 

I see minor problem with the spacing between API element and its description:

**Before:**
image

**After:**
image

**Comment by rlnx** [comment]
Seems like the problem with spacing is fixed by adding extra margin to `dd`
```css
.rst-content dl dd {
    margin-top: 6px;
}
```

**Comment by rsdubtso** [comment]
> Seems like the problem with spacing is fixed by adding extra margin to `dd`
> 
> ```css
> .rst-content dl dd {
>     margin-top: 6px;
> }
> ```

Thanks, that's a good catch. I've pushed a new version (with a lightly more restricted modifier):
```css
.rst-content dl:not(.docutils) dd {
    margin-top: 6px;
}
```

**Comment by rscohn2** [comment]
@zackwaters FYI

**Pull request merged**
