### PR TITLE
[DO NOT MERGE] Fix rendering of custom latex commands in html spec

### PR DESCRIPTION
**Pull request by mgouicem**
I tried to add the custom latex commands in common_conf.py, however, it still does not render properly in html build. Any idea?

image

Though it works with the same variables setting when building the oneDNN component spec only

image

### CODE REVIEW

**Comment by mgouicem** [comment]
@rscohn2 for potential ideas on how to fix this rendering issue.

**Comment by rscohn2** [comment]
Works for me 
image

**Comment by rscohn2** [comment]
CI generated build is ok, too: https://oneapi-src.github.io/oneAPI-spec/spec/elements/oneDNN/source/primitives/convolution.html

Are you done with changes?

**Comment by mgouicem** [comment]
Great! Yes done with changes. Thanks a lot for the help and patience!

**Pull request merged**
