### PR TITLE
[oneMKL][BLAS] Fix syr*k typo

### PR DESCRIPTION
**Pull request by mmeterel**
This PR is closing #462

### CODE REVIEW

**Comment by mmeterel** [comment]
@andrewtbarker Could you please take a look at this?

**Review by andrewtbarker — APPROVED** [review]
This looks right to me. I wish we could somehow use the same source for the DPCPP docs and in the spec?

**Comment by mmeterel** [comment]
@rscohn2 I see the CI checks are failing. I don't think it is related to this PR. Do you have any idea?

**Comment by mmeterel** [comment]
> This looks right to me. I wish we could somehow use the same source for the DPCPP docs and in the spec?

Thanks for checking. Agreed, that has been my hope since we switched to github for DPCPP docs, but I believe there are some format differences and list of exceptions (spec has, docs don't). I don't think these are showstoppers though.

**Comment by mmeterel** [comment]
> @rscohn2 I see the CI checks are failing. I don't think it is related to this PR. Do you have any idea?

@rscohn2 ping

**Comment by rscohn2** [comment]
Can you sync your fork? I believe it will clear the checker error. Go here:
https://github.com/alexandraepan/oneAPI-spec
There should be a Sync fork drop-down below the green <> Code button

**Pull request merged**
