### PR TITLE
[oneDPL] Add section about how to pass data to algorithms

### PR DESCRIPTION
**Pull request by capatober**
It clarifies how user can pass data to oneDPL algorithms

### CODE REVIEW

**Comment by akukanov** [comment]
I do not like it. The wording would be good for a user manual, but not good for the specification which should be more formal and oriented towards implementers, not users. The placement of this in the middle of API description is also not quite right.

**Comment by capatober** [comment]
@akukanov, thanks for the feedback!
Do you mean the wording and placement only or the thing that we need this changes in the Spec as well?
If it's just about wording then would the following wording be better?
```
There are 2 forms of data that can be passed to oneDPL algorithms executed with a DPC++ policy:
...
Passing others as a data to algorithms executed with a DPC++ policy leads to undefined behavior.
```

I've placed it here because the Buffer wrappers section is mentioned in the changes and it seemed as a good idea to place the changes before the Buffer wrappers section. It looks like:
```
1. Policies.
2. Forms of data that are accepted by algorithms.
2.a. or 3. Buffer wrappers
```
I also see another way:
```
1. Algorithms and data accepted by algorithms.
2. Specific API
2.a. Policies
2.b. Buffer wrappers
```
Is it better?

**Comment by rscohn2** [comment]
I am making a release. Can you merge or close this?

**Comment by rscohn2** [comment]
I am closing because this has been inactive. You can reopen if you are still working on it.

**Pull request closed without merging**
